### ISSUE TITLE
Code crashes if training data is too small

### ISSUE THREAD

**Issue by jcklie** [inception-project/external-recommender-flair#25]
If I have very few annotations for training, like 1, then the training crashes:

```
2019-08-26 15:21:16,738 127.0.0.1 - - [26/Aug/2019 15:21:16] "POST /ner/train HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/klie/git/students/external-recommender-flair/app_flair.py", line 75, in route_train_ner
    train, dev = parse_ner_train_request(json_data)
  File "/home/klie/git/students/external-recommender-flair/app_flair.py", line 183, in parse_ner_train_request
    train, dev, = train_test_split(list_sentences, train_size=0.8)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 2100, in train_test_split
    default_test_size=0.25)
  File "/home/klie/git/students/external-recommender-flair/venv/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 1782, in _validate_shuffle_split
    train_size)
ValueError: With n_samples=1, test_size=None and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.

```

**Comment by bjtulinl** [comment]
It seems if the size of annotations is too small then they can't be split into train and dev sets. So should this train be discarded for this situation?

**Comment by jcklie** [comment]
Yes
